name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-sonarqube:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest pytest-cov httpx

      - run: echo "PYTHONPATH=$(pwd)/src:$PYTHONPATH" >> $GITHUB_ENV

      - run: pytest --cov=src --cov-branch --cov-report=xml:coverage.xml

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t fastapi-calculator .

      - name: Start App Container
        run: |
          docker network create zapnet
          docker run -d --network zapnet --name fastapi-app -p 8000:8000 fastapi-calculator
          sleep 10

      - name: OWASP ZAP Baseline Scan
        run: |
          mkdir zap-output
          chmod 777 zap-output
          docker run --rm --network zapnet \
            -v $(pwd)/zap-output:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:stable \
            /zap/zap-baseline.py \
            -t http://fastapi-app:8000 \
            --autooff \
            -I \
            -x zap-report.xml \
            -r zap-report.html \
            -J zap-report.json \
            -w zap-warnings.md

      - uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-output/*

      - uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_SCANNER_OPTS: -Dsonar.python.coverage.reportPaths=coverage.xml
